### ISSUE TITLE
Set up Travis CI for puppet-hilary

### ISSUE THREAD

**Issue by simong** [oaeproject/puppet-hilary#130]
We should enable Travis CI for our commits to puppet-hilary. It should:
 - check that all the hiera json files are valid JSON, this was silently breaking a deploy
 - maybe check that known secure keys aren't committed into the repo
 - do basic puppet linting (although it might be too much work to adhere to the full standard, some quick sanity-checking would be helpful)

**Comment by simong** [comment]
Assigning to @davidoae

**Comment by davidoae** [comment]
did a quick lint of puppet-hilary;
1249 WARNINGs, things like extra spaces and non-standard indents
12 ERRORs, mostly moaning about tabs
3 ERRORs look genuine;
.//modules/oaeservice/manifests/nagios/disk.pp - ERROR: oaeservice::nagios::disk::shared not in autoload module layout on line 31
.//modules/oaeservice/manifests/nagios/syslog.pp - ERROR: oaeservice::nagios::syslog::server not in autoload module layout on line 1
.//modules/oaeservice/manifests/backup/init.pp - ERROR: oaeservice::backup not in autoload module layout on line 1

I suspect most of the WARNINGs would be resolved by asking puppet-lint to fix them.

**Comment by simong** [comment]
Fixed in #144
