### ISSUE TITLE
Disk space keeps getting filled up on the QA servers

### ISSUE THREAD

**Issue by simong** [oaeproject/puppet-hilary#151]
I'm fairly ambivalent about how this gets solved but maybe we should map a few big offenders (apt cache, cassandra, ..) to `/data` through puppet?

**Comment by davidoae** [comment]
Cassandra already uses /data/cassandra/ however the commit log is stored in /var/lib/cassandra/commitlog and is ~1G both in qa and prod.
This is presumably configurable.
We'll have to have a quick chat to see if we want to do this as it may have a performance impact having the commit log on the same volume as the data.

As this only seems to effect qa maybe we should move /opt to the /data drive.
I'll sort a cron for apt-get clean as that's an easy win.

**Comment by davidoae** [comment]
Some time ago qa was cleaned up some to ensure suitable space available.
I don't believe we need this ticket now, a new issue can be created if problems arise once more.
