### ISSUE TITLE
Update NTP configuration to minimize relative clock drift

### ISSUE THREAD

**Issue by mrvisser** [oaeproject/puppet-hilary#152]
I think both ideal and simplest scenario seems to be to nominate an NTP master (bastion? monitor? puppet? dedicated `time` node?) in our infrastructure that synchronizes externally, while at the least our DB nodes synchronize to it. I don't think we need a high-availability pool of NTP masters at the moment.

This recommendation is based on reading through this series of blog posts:

https://blog.logentries.com/2014/03/synchronizing-clocks-in-a-cassandra-cluster-pt-1-the-problem/
https://blog.logentries.com/2014/03/synchronizing-clocks-in-a-cassandra-cluster-pt-2-solutions/

... and noticing log entries indicating our Cassandra nodes drop in and out of gossip occasionally.

**Comment by mrvisser** [comment]
@davidoae would you mind having a look at this?

**Comment by davidoae** [comment]
Checked all ntp configs, all looks good. The ntp config is provided by joyent and is sensible.
Also created nagios check for ntp drift. The monitoring should make it easy to see if servers are drifting too far, at which point we'll re-evaluate.

**Comment by mrvisser** [comment]
Thanks @davidoae !
