### ISSUE TITLE
Server maintenance page blank

### ISSUE THREAD

**Issue by davidoae** [oaeproject/puppet-hilary#163]
Using chromium v43, although a page is returned it looks blank to the user.
This is an inactive tenancy;
https://unity.oaeproject.org/servermaintenance

I note that a tenancy that has never existed doesn't get redirected to server maintenance page;
https://dcwuiegfisbcf.unity.ac/

**Comment by mrvisser** [comment]
As mentioned in slack, it is working as expected.

**Comment by nicolaasmatthijs** [comment]
Actually, the server maintenance page should not be blank. @sathomas : Would you be able to have a look at this?

**Comment by mrvisser** [comment]
Should also note that it seems to be blank with active tenancies too:

https://oae.gatech.edu/servermaintenance

**Comment by sathomas** [comment]
Moving this to https://github.com/oaeproject/3akai-ux/issues/4037
