### ISSUE TITLE
Define way in which redirects can easily be configured

### ISSUE THREAD

**Issue by nicolaasmatthijs** [oaeproject/puppet-hilary#181]
Define way in which redirects can easily be configured

**Comment by nicolaasmatthijs** [comment]
Assigning to @davidoae for initial proposal

**Comment by davidoae** [comment]
The consensus is to use nginx map function to perform this as it involves the least work and we're not currently sure how this is going to play out in the long run.

We can add a new nginx config file to puppet, include that file in the main config and add a rewrite that uses it.
The redirect map would be managed by admins/devs as it requires puppet changes.
We can also move our older redirects to this system.

# oae.conf.d/00-redirectmap.conf
map $host $redirect_host {
  hostnames;

  one.david.org eleven.david.org;
  two.david.org twelve.steve.org;
}

# oae.d.conf/unity.ac.conf
# within server { } config
  if ($redirect_host) {
    return 301 $scheme://$redirect_host$request_uri;
  }

**Comment by davidoae** [comment]
Bummer, can't be used by older redirects as the ssl certificate will not match.
Will only work for unity.ac -> unity.ac

hmm

**Comment by davidoae** [comment]
OK, if every server {} has the redirect in and we include a server {} for each domain (oaeproject.org) rather than a server for each subdomain (bath.oaeproject.org) this should still work as desired.
I'll test this nowish.

**Comment by davidoae** [comment]
I've implemented this for unity.ac hosts only for the moment, although we can easily expand as required.
https://github.com/oaeproject/puppet-hilary/pull/184

**Comment by davidoae** [comment]
This has been done and is being used in production.
https://github.com/oaeproject/puppet-hilary/pull/184
